version: "3.8"

services:
  next:
    build: ./
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file: ./.env

  postgres:
    restart: always
    env_file: ./.env
    image: postgres:12
    volumes:
      - project-hawker-dev:/var/lib/postgresql/data
    expose:
      - "5432"

  adminer:
    image: adminer
    ports:
      - 8081:8080
    logging:
      driver: none

volumes:
  project-hawker-dev:
