version: "3.8"

services:
  next:
    build: ./
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file: ./.env

  postgres:
    restart: always
    env_file: ./.env
    image: postgres:12
    volumes:
      - project-hawker-dev:/var/lib/postgresql/data
    expose:
      - "5432"

  adminer:
    image: adminer
    ports:
      - 8081:8080
    logging:
      driver: none

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-dev:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    build: ./logstash
    env_file: ./.env

volumes:
  project-hawker-dev:
  es-dev:
