version: "3.8"

services:
  next:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.production   
    ports:
      - 3000:3000
    env_file: ./.env

  postgres:
    restart: always
    env_file: ./.env
    image: postgres:12
    volumes:
      - project-hawker:/var/lib/postgresql/data
    expose:
      - "5432"

  adminer:
    restart: always
    image: adminer
    ports:
      - 8081:8080
    logging:
      driver: none

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    mem_limit: 2g

  logstash:
    build: ./logstash
    env_file: ./.env

volumes:
  project-hawker:
  es:
